# Generated by Django 5.2.7 on 2026-05-20 22:56

import AppCore.core.business.business_mixin
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_academico', models.EmailField(blank=True, max_length=254, verbose_name='E-mail acadêmico')),
                ('email_pessoal', models.EmailField(blank=True, max_length=254, verbose_name='E-mail pessoal')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
            bases=(AppCore.core.business.business_mixin.ModelBusinessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('email_academico', models.EmailField(blank=True, max_length=254, verbose_name='E-mail acadêmico')),
                ('email_pessoal', models.EmailField(blank=True, max_length=254, verbose_name='E-mail pessoal')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Contato',
                'verbose_name_plural': 'historical Contatos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
