# Generated by Django 5.2.7 on 2026-05-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['usuario__nome'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
