# Generated by Django 5.2.14 on 2026-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contato_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicalcontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone'),
        ),
    ]
