# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalaSetor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Vínculo Sala–Setor',
                'verbose_name_plural': 'historical Vínculos Sala–Setor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['bloco__nome', 'nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SalaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vínculo Sala–Setor',
                'verbose_name_plural': 'Vínculos Sala–Setor',
                'ordering': ['sala__bloco__nome', 'sala__nome', 'setor__nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSala',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bloco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blocos.bloco', verbose_name='Bloco')),
            ],
            options={
                'verbose_name': 'historical Sala',
                'verbose_name_plural': 'historical Salas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
