# Generated by Django 5.2.14 on 2026-07-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['bloco__nome', 'nome'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='salasetor',
            options={'ordering': ['sala__bloco__nome', 'sala__nome', 'setor__nome'], 'verbose_name': 'Vínculo Sala–Setor', 'verbose_name_plural': 'Vínculos Sala–Setor'},
        ),
    ]
