# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocos', '0002_initial'),
        ('salas', '0001_initial'),
        ('setores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsala',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalasetor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalasetor',
            name='setor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setores.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='sala',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='blocos.bloco', verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='historicalsalasetor',
            name='sala',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salas.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='salasetor',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores_vinculados', to='salas.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='salasetor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas_vinculadas', to='setores.setor', verbose_name='Setor'),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('bloco', 'nome'), name='salas_sala_bloco_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='salasetor',
            constraint=models.UniqueConstraint(fields=('sala', 'setor'), name='salas_salasetor_sala_setor_unico'),
        ),
    ]
