# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPermissaoUsuarioInfraestrutura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('operar', models.BooleanField(default=False, verbose_name='Operar')),
                ('cadastrar', models.BooleanField(default=False, verbose_name='Cadastrar')),
                ('autorizar', models.BooleanField(default=False, verbose_name='Autorizar')),
                ('retirada_irrestrita', models.BooleanField(default=False, verbose_name='Retirada irrestrita')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Permissão de Infraestrutura por Usuário',
                'verbose_name_plural': 'historical Permissões de Infraestrutura por Usuário',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PermissaoFuncaoInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operar', models.BooleanField(default=False, verbose_name='Operar')),
                ('cadastrar', models.BooleanField(default=False, verbose_name='Cadastrar')),
                ('autorizar', models.BooleanField(default=False, verbose_name='Autorizar')),
                ('retirada_irrestrita', models.BooleanField(default=False, verbose_name='Retirada irrestrita')),
            ],
            options={
                'verbose_name': 'Permissão de Infraestrutura por Função',
                'verbose_name_plural': 'Permissões de Infraestrutura por Função',
                'ordering': ['funcao__papel_funcao'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PermissaoUsuarioInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operar', models.BooleanField(default=False, verbose_name='Operar')),
                ('cadastrar', models.BooleanField(default=False, verbose_name='Cadastrar')),
                ('autorizar', models.BooleanField(default=False, verbose_name='Autorizar')),
                ('retirada_irrestrita', models.BooleanField(default=False, verbose_name='Retirada irrestrita')),
            ],
            options={
                'verbose_name': 'Permissão de Infraestrutura por Usuário',
                'verbose_name_plural': 'Permissões de Infraestrutura por Usuário',
                'ordering': ['usuario__nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPermissaoFuncaoInfraestrutura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('operar', models.BooleanField(default=False, verbose_name='Operar')),
                ('cadastrar', models.BooleanField(default=False, verbose_name='Cadastrar')),
                ('autorizar', models.BooleanField(default=False, verbose_name='Autorizar')),
                ('retirada_irrestrita', models.BooleanField(default=False, verbose_name='Retirada irrestrita')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('funcao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funcoes.funcao', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'historical Permissão de Infraestrutura por Função',
                'verbose_name_plural': 'historical Permissões de Infraestrutura por Função',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
