# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcoes', '0002_initial'),
        ('permissoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermissaofuncaoinfraestrutura',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpermissaousuarioinfraestrutura',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpermissaousuarioinfraestrutura',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='permissaofuncaoinfraestrutura',
            name='funcao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permissao_infraestrutura', to='funcoes.funcao', verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='permissaousuarioinfraestrutura',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permissao_infraestrutura', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
