# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import simple_history.models
from django.db import migrations, models


def inserir_cargos_raizes(apps, schema_editor):
    Cargo = apps.get_model('cargos', 'Cargo')

    cargos = [
        {"nome": "PROF ENS BAS TEC TECNOLOGICO-SUBSTITUTO", "ativo": True},
        {"nome": "ASSISTENTE EM ADMINISTRACAO", "ativo": True},
        {"nome": "ASSISTENTE DE ALUNO", "ativo": True},
        {"nome": "ADMINISTRADOR", "ativo": True},
        {"nome": "TEC DE TECNOLOGIA DA INFORMACAO", "ativo": True},
        {"nome": "PROFESSOR ENS BASICO TECN TECNOLOGICO", "ativo": True},
        {"nome": "ENGENHEIRO", "ativo": True},
        {"nome": "BIBLIOTECARIO-DOCUMENTALISTA", "ativo": True},
        {"nome": "VIGILANTE", "ativo": True},
        {"nome": "TECNICO EM AUDIOVISUAL", "ativo": True},
        {"nome": "CONTADOR", "ativo": True},
        {"nome": "AUXILIAR DE BIBLIOTECA", "ativo": True},
        {"nome": "AUX EM ADMINISTRACAO", "ativo": True},
        {"nome": "ENFERMEIRO", "ativo": True},
        {"nome": "TECNICO EM ELETROTECNICA", "ativo": True},
        {"nome": "TECNICO DE LABORATORIO AREA", "ativo": True},
        {"nome": "PSICOLOGO", "ativo": True},
        {"nome": "TECNICO EM ARQUIVO", "ativo": True},
        {"nome": "ASSISTENTE SOCIAL", "ativo": True},
        {"nome": "TECNICO EM ASSUNTOS EDUCACIONAIS", "ativo": True},
        {"nome": "ODONTOLOGO", "ativo": True},
        {"nome": "SECRETARIO EXECUTIVO", "ativo": True},
        {"nome": "PEDAGOGO", "ativo": True},
        {"nome": "ASSISTENTE DE LABORATORIO", "ativo": True},
        {"nome": "NUTRICIONISTA", "ativo": True},
        {"nome": "MEDICO", "ativo": True},
        {"nome": "TECNICO EM ENFERMAGEM", "ativo": True},
        {"nome": "TECNICO EM SECRETARIADO", "ativo": True},
        {"nome": "ANALISTA DE TEC DA INFORMACAO", "ativo": True},
    ]

    for cargo_data in cargos:
        Cargo.objects.get_or_create(
            nome=cargo_data['nome'],
            defaults={
                'ativo': cargo_data['ativo'],
            }
        )


def remover_cargos_raizes(apps, schema_editor):
    Cargo = apps.get_model('cargos', 'Cargo')
    nomes = [
        "PROF ENS BAS TEC TECNOLOGICO-SUBSTITUTO",
        "ASSISTENTE EM ADMINISTRACAO",
        "ASSISTENTE DE ALUNO",
        "ADMINISTRADOR",
        "TEC DE TECNOLOGIA DA INFORMACAO",
        "PROFESSOR ENS BASICO TECN TECNOLOGICO",
        "ENGENHEIRO",
        "BIBLIOTECARIO-DOCUMENTALISTA",
        "VIGILANTE",
        "TECNICO EM AUDIOVISUAL",
        "CONTADOR",
        "AUXILIAR DE BIBLIOTECA",
        "AUX EM ADMINISTRACAO",
        "ENFERMEIRO",
        "TECNICO EM ELETROTECNICA",
        "TECNICO DE LABORATORIO",
        "PSICOLOGO",
        "TECNICO EM ARQUIVO",
        "ASSISTENTE SOCIAL",
        "TECNICO EM ASSUNTOS EDUCACIONAIS",
        "ODONTOLOGO - 40 HORAS",
        "SECRETARIO EXECUTIVO",
        "PEDAGOGO",
        "ASSISTENTE DE LABORATORIO",
        "NUTRICIONISTA-HABILITACAO",
        "MEDICO - PCCTAE",
        "TECNICO EM ENFERMAGEM",
        "TECNICO EM SECRETARIADO",
        "ANALISTA DE TEC DA INFORMACAO",
    ]
    Cargo.objects.filter(nome__in=nomes).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCargo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cargo',
                'verbose_name_plural': 'historical Cargos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(inserir_cargos_raizes, reverse_code=remover_cargos_raizes),
    ]
