# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('percursos', '0002_initial'),
        ('rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrota',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrota',
            name='percurso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='percursos.percurso', verbose_name='Percurso'),
        ),
        migrations.AddField(
            model_name='rota',
            name='percurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='percursos.percurso', verbose_name='Percurso'),
        ),
        migrations.AddConstraint(
            model_name='rota',
            constraint=models.UniqueConstraint(fields=('percurso', 'dia_semana', 'horario_saida'), name='rotas_rota_percurso_dia_horario_unico'),
        ),
        migrations.AddConstraint(
            model_name='rota',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_vagas__gte', 1)), name='rotas_rota_vagas_minimo_1'),
        ),
    ]
