# Generated by Django 5.2.14 on 2026-10-05 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percursos', '0002_initial'),
        ('rotas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrota',
            name='dias_antecedencia_abertura',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No mesmo dia'), (1, 'No dia anterior')], default=1, verbose_name='Dia de abertura das solicitações'),
        ),
        migrations.AddField(
            model_name='historicalrota',
            name='horario_abertura_solicitacoes',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Horário de abertura das solicitações'),
        ),
        migrations.AddField(
            model_name='rota',
            name='dias_antecedencia_abertura',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No mesmo dia'), (1, 'No dia anterior')], default=1, verbose_name='Dia de abertura das solicitações'),
        ),
        migrations.AddField(
            model_name='rota',
            name='horario_abertura_solicitacoes',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='Horário de abertura das solicitações'),
        ),
        migrations.AddConstraint(
            model_name='rota',
            constraint=models.CheckConstraint(condition=models.Q(('dias_antecedencia_abertura__in', [0, 1])), name='rota_antecedencia_abertura_valida'),
        ),
    ]
