# Generated by Django 5.2.14 on 2026-10-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0005_remover_antecedencia_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrota',
            name='horario_abertura_solicitacoes',
            field=models.TimeField(verbose_name='Horário de abertura das solicitações'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='horario_abertura_solicitacoes',
            field=models.TimeField(verbose_name='Horário de abertura das solicitações'),
        ),
    ]
