# Generated by Django 5.2.14 on 2026-09-14 21:05

from django.db import migrations, models


def conceder_relatorio_a_funcoes_gestoras(apps, schema_editor):
    Funcao = apps.get_model('funcoes', 'Funcao')
    PermissaoFuncaoTransporte = apps.get_model(
        'transporte_permissoes',
        'PermissaoFuncaoTransporte',
    )

    categorias_gestoras = ('diretor', 'coordenador', 'chefe')
    for funcao_id in Funcao.objects.filter(
        categoria__in=categorias_gestoras,
    ).values_list('pk', flat=True):
        permissao, _ = PermissaoFuncaoTransporte.objects.get_or_create(
            funcao_id=funcao_id,
        )
        if not permissao.visualizar_relatorio_alunos:
            permissao.visualizar_relatorio_alunos = True
            permissao.save(update_fields=['visualizar_relatorio_alunos'])


class Migration(migrations.Migration):

    dependencies = [
        ('transporte_permissoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermissaofuncaotransporte',
            name='visualizar_relatorio_alunos',
            field=models.BooleanField(default=False, verbose_name='Visualizar relatório de alunos'),
        ),
        migrations.AddField(
            model_name='historicalpermissaousuariotransporte',
            name='visualizar_relatorio_alunos',
            field=models.BooleanField(default=False, verbose_name='Visualizar relatório de alunos'),
        ),
        migrations.AddField(
            model_name='permissaofuncaotransporte',
            name='visualizar_relatorio_alunos',
            field=models.BooleanField(default=False, verbose_name='Visualizar relatório de alunos'),
        ),
        migrations.AddField(
            model_name='permissaousuariotransporte',
            name='visualizar_relatorio_alunos',
            field=models.BooleanField(default=False, verbose_name='Visualizar relatório de alunos'),
        ),
        migrations.RunPython(
            conceder_relatorio_a_funcoes_gestoras,
            migrations.RunPython.noop,
        ),
    ]
