# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.rules.rules_mixin
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImportacaoLote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('arquivo', models.TextField(max_length=100, verbose_name='Arquivo de Importação')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('total_linhas', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('linhas_processadas', models.IntegerField(default=0, verbose_name='Linhas Processadas')),
                ('resultado_json', models.JSONField(blank=True, null=True, verbose_name='Resultado/Erros')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Importação de Lote de Infraestrutura',
                'verbose_name_plural': 'historical Importações de Lote de Infraestrutura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportacaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='importacoes/infraestrutura/%Y/%m/%d/', verbose_name='Arquivo de Importação')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('total_linhas', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('linhas_processadas', models.IntegerField(default=0, verbose_name='Linhas Processadas')),
                ('resultado_json', models.JSONField(blank=True, null=True, verbose_name='Resultado/Erros')),
            ],
            options={
                'verbose_name': 'Importação de Lote de Infraestrutura',
                'verbose_name_plural': 'Importações de Lote de Infraestrutura',
                'ordering': ['-created_at'],
            },
            bases=(AppCore.core.rules.rules_mixin.ModelRulesMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, models.Model),
        ),
    ]
