# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportacaolote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='importacaolote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'EM_ANDAMENTO')), fields=('status',), name='importacoes_infraestrutura_lote_unico_em_andamento'),
        ),
    ]
