# Generated by Django 5.2.14 on 2026-08-29 19:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpercurso',
            name='apelido',
            field=models.CharField(max_length=255, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='percurso',
            name='apelido',
            field=models.CharField(max_length=255, verbose_name='Apelido'),
        ),
        migrations.AddConstraint(
            model_name='percurso',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('apelido'), name='percursos_percurso_apelido_lower_unico'),
        ),
    ]
