# Generated by Django 5.2.7 on 2026-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservidor',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Professor'), (2, 'Tec.Administrativo')], verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Professor'), (2, 'Tec.Administrativo')], verbose_name='Categoria'),
        ),
    ]
