# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0002_initial'),
        ('servidores', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservidor',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargos.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalservidor',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='servidor', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('categoria', models.IntegerField(choices=[(1, 'Professor'), (2, 'Tec.Administrativo')], verbose_name='Categoria')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='cargos.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['usuario__nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('matricula__isnull', False)), fields=('matricula',), name='servidores_matricula_unica')],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
    ]
