# Generated by Django 5.2.14 on 2026-05-24 06:57

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alter_aluno_options'),
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_cursos', to='alunos.aluno', verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_vinculados', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Vínculo Aluno-Curso',
                'verbose_name_plural': 'Vínculos Aluno-Curso',
                'ordering': ['-created_at'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAlunoCurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aluno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alunos.aluno', verbose_name='Aluno')),
                ('curso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cursos.curso', verbose_name='Curso')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vínculo Aluno-Curso',
                'verbose_name_plural': 'historical Vínculos Aluno-Curso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
