# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('ira', models.FloatField(blank=True, null=True, verbose_name='IRA')),
                ('turma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('situacao_curso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação do Curso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Vínculo Aluno-Curso',
                'verbose_name_plural': 'Vínculos Aluno-Curso',
                'ordering': ['aluno__usuario__nome', 'curso__nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAlunoCurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('ira', models.FloatField(blank=True, null=True, verbose_name='IRA')),
                ('turma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('situacao_curso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação do Curso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Vínculo Aluno-Curso',
                'verbose_name_plural': 'historical Vínculos Aluno-Curso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
