# Generated by Django 5.2.14 on 2026-07-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunocurso',
            options={'ordering': ['aluno__usuario__nome', 'curso__nome'], 'verbose_name': 'Vínculo Aluno-Curso', 'verbose_name_plural': 'Vínculos Aluno-Curso'},
        ),
    ]
