# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno_cursos', '0001_initial'),
        ('alunos', '0001_initial'),
        ('cursos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alunocurso',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_cursos', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='alunocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_vinculados', to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='historicalalunocurso',
            name='aluno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='historicalalunocurso',
            name='curso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='historicalalunocurso',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='alunocurso',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula__isnull', False)), fields=('matricula',), name='aluno_cursos_matricula_unica'),
        ),
    ]
