# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import AppCore.core.state.state_mixin
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_execucao', models.DateField(verbose_name='Data da execução')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data e hora de saída')),
                ('quantidade_vagas', models.PositiveIntegerField(verbose_name='Quantidade de vagas')),
                ('status', models.IntegerField(choices=[(1, 'Reservas abertas'), (2, 'Reservas fechadas'), (3, 'Em embarque'), (4, 'Finalizada'), (5, 'Cancelada'), (6, 'Embarcado'), (7, 'Iniciada')], default=1, verbose_name='Status')),
                ('chamada_tickets_concluida', models.BooleanField(default=False, verbose_name='Chamada de tickets concluída')),
                ('monitoramento_iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Monitoramento iniciado em')),
                ('chamada_concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Chamada concluída em')),
                ('embarcado_em', models.DateTimeField(blank=True, null=True, verbose_name='Embarcado em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('chamada_ausentes_codigos', models.JSONField(blank=True, default=list, verbose_name='Códigos ausentes da chamada')),
                ('entradas_cpf_concluidas', models.BooleanField(default=False, verbose_name='Entrada por CPF concluída')),
                ('entradas_cpf_concluidas_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrada por CPF concluída em')),
                ('entradas_cpf_codigos', models.JSONField(blank=True, default=list, verbose_name='CPFs do lote da conferência')),
                ('rota_iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='Rota iniciada em')),
                ('rota_finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Rota finalizada em')),
            ],
            options={
                'verbose_name': 'Execução de rota',
                'verbose_name_plural': 'Execuções de rotas',
                'ordering': ['data_hora_saida', 'rota_id'],
            },
            bases=(AppCore.core.state.state_mixin.ModelStateMixin, AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExecucaoRota',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('data_execucao', models.DateField(verbose_name='Data da execução')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data e hora de saída')),
                ('quantidade_vagas', models.PositiveIntegerField(verbose_name='Quantidade de vagas')),
                ('status', models.IntegerField(choices=[(1, 'Reservas abertas'), (2, 'Reservas fechadas'), (3, 'Em embarque'), (4, 'Finalizada'), (5, 'Cancelada'), (6, 'Embarcado'), (7, 'Iniciada')], default=1, verbose_name='Status')),
                ('chamada_tickets_concluida', models.BooleanField(default=False, verbose_name='Chamada de tickets concluída')),
                ('monitoramento_iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Monitoramento iniciado em')),
                ('chamada_concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Chamada concluída em')),
                ('embarcado_em', models.DateTimeField(blank=True, null=True, verbose_name='Embarcado em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('chamada_ausentes_codigos', models.JSONField(blank=True, default=list, verbose_name='Códigos ausentes da chamada')),
                ('entradas_cpf_concluidas', models.BooleanField(default=False, verbose_name='Entrada por CPF concluída')),
                ('entradas_cpf_concluidas_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrada por CPF concluída em')),
                ('entradas_cpf_codigos', models.JSONField(blank=True, default=list, verbose_name='CPFs do lote da conferência')),
                ('rota_iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='Rota iniciada em')),
                ('rota_finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Rota finalizada em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Execução de rota',
                'verbose_name_plural': 'historical Execuções de rotas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
