# Generated by Django 5.2.14 on 2026-08-31 18:50

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import AppCore.core.state.state_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExecucaoRota',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('data_execucao', models.DateField(verbose_name='Data da execução')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data e hora de saída')),
                ('quantidade_vagas', models.PositiveIntegerField(verbose_name='Quantidade de vagas')),
                ('status', models.IntegerField(choices=[(1, 'Reservas abertas'), (2, 'Reservas fechadas'), (3, 'Em embarque'), (4, 'Finalizada'), (5, 'Cancelada')], default=1, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rota', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotas.rota', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'historical Execução de rota',
                'verbose_name_plural': 'historical Execuções de rotas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExecucaoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_execucao', models.DateField(verbose_name='Data da execução')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data e hora de saída')),
                ('quantidade_vagas', models.PositiveIntegerField(verbose_name='Quantidade de vagas')),
                ('status', models.IntegerField(choices=[(1, 'Reservas abertas'), (2, 'Reservas fechadas'), (3, 'Em embarque'), (4, 'Finalizada'), (5, 'Cancelada')], default=1, verbose_name='Status')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='rotas.rota', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Execução de rota',
                'verbose_name_plural': 'Execuções de rotas',
                'ordering': ['data_hora_saida', 'rota_id'],
                'constraints': [models.UniqueConstraint(fields=('rota', 'data_execucao'), name='execucao_rota_unica_por_data'), models.CheckConstraint(condition=models.Q(('quantidade_vagas__gte', 1)), name='execucao_rota_vagas_minimo_1')],
            },
            bases=(AppCore.core.state.state_mixin.ModelStateMixin, AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
    ]
