# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execucoes_rotas', '0001_initial'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaorota',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='rotas.rota', verbose_name='Rota'),
        ),
    ]
