# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execucoes_rotas', '0002_initial'),
        ('rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaorota',
            name='rota_iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Rota iniciada por'),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='rota',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotas.rota', verbose_name='Rota'),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='rota_iniciada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Rota iniciada por'),
        ),
        migrations.AddConstraint(
            model_name='execucaorota',
            constraint=models.CheckConstraint(condition=models.Q(('rota_finalizada_em__isnull', True), models.Q(('rota_iniciada_em__isnull', False), ('rota_finalizada_em__gte', models.F('rota_iniciada_em'))), _connector='OR'), name='execucao_rota_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='execucaorota',
            constraint=models.UniqueConstraint(fields=('rota', 'data_execucao'), name='execucao_rota_unica_por_data'),
        ),
        migrations.AddConstraint(
            model_name='execucaorota',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_vagas__gte', 1)), name='execucao_rota_vagas_minimo_1'),
        ),
    ]
