# Generated by Django 5.2.14 on 2026-09-11 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes_rotas', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaorota',
            name='conferencia_finalizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Conferência finalizada por'),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='conferencia_finalizada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Conferência finalizada por'),
        ),
    ]
