# Generated by Django 5.2.14 on 2026-09-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes_rotas', '0004_chamada_ausentes'),
        ('rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaorota',
            name='rota_finalizada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota finalizada em'),
        ),
        migrations.AddField(
            model_name='execucaorota',
            name='rota_iniciada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota iniciada em'),
        ),
        migrations.AddField(
            model_name='execucaorota',
            name='rota_iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Rota iniciada por'),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='rota_finalizada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota finalizada em'),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='rota_iniciada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota iniciada em'),
        ),
        migrations.AddField(
            model_name='historicalexecucaorota',
            name='rota_iniciada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Rota iniciada por'),
        ),
        migrations.AddConstraint(
            model_name='execucaorota',
            constraint=models.CheckConstraint(condition=models.Q(('rota_finalizada_em__isnull', True), models.Q(('rota_iniciada_em__isnull', False), ('rota_finalizada_em__gte', models.F('rota_iniciada_em'))), _connector='OR'), name='execucao_rota_fim_apos_inicio'),
        ),
    ]
