# Generated by Django 5.2.14 on 2026-09-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes_rotas', '0005_viagem_motorista'),
        ('execucoes_rotas', '0006_embarcado_em'),
    ]

    operations = [
    ]
