# Generated by Django 5.2.14 on 2026-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes_rotas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaorota',
            name='status',
            field=models.IntegerField(
                choices=[
                    (1, 'Reservas abertas'),
                    (2, 'Reservas fechadas'),
                    (3, 'Em embarque'),
                    (4, 'Finalizada'),
                    (5, 'Cancelada'),
                    (6, 'Embarcado'),
                    (7, 'Iniciada'),
                ],
                default=1,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexecucaorota',
            name='status',
            field=models.IntegerField(
                choices=[
                    (1, 'Reservas abertas'),
                    (2, 'Reservas fechadas'),
                    (3, 'Em embarque'),
                    (4, 'Finalizada'),
                    (5, 'Cancelada'),
                    (6, 'Embarcado'),
                    (7, 'Iniciada'),
                ],
                default=1,
                verbose_name='Status',
            ),
        ),
    ]
