# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import AppCore.core.users_permissions.user_permission_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cargos', '0001_initial'),
        ('empresas_instituicoes', '0001_initial'),
        ('funcoes', '0001_initial'),
        ('setores', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('foto', models.URLField(blank=True, help_text='URL pública da foto vinda de sistemas externos.', max_length=500, null=True, verbose_name='Foto primária')),
                ('foto_secundaria', models.CharField(blank=True, help_text='Chave S3 da foto enviada pelo próprio usuário (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto secundária')),
                ('deficiencia', models.CharField(blank=True, choices=[('deficiencia_intelectual', 'Deficiência Intelectual'), ('deficiencia_visual', 'Deficiência Visual'), ('deficiencia_auditiva', 'Deficiência Auditiva'), ('deficiencia_multipla', 'Deficiência Múltipla'), ('deficiencia_fisica', 'Deficiência Física')], max_length=50, null=True, verbose_name='Deficiência / necessidade especial')),
                ('colaborador_externo', models.BooleanField(default=False, help_text='Indica se o usuário é colaborador externo à instituição.', verbose_name='Colaborador externo')),
                ('usuario_coletivo', models.BooleanField(default=False, help_text='Conta compartilhada (ex.: guarita). No empréstimo, o responsável deve ser escolhido entre os usuários do pool associado.', verbose_name='Usuário coletivo')),
                ('cargos_coletivo', models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_cargo', to='cargos.cargo', verbose_name='Cargos do pool coletivo')),
                ('empresas_coletivo', models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_empresa', to='empresas_instituicoes.empresainstituicao', verbose_name='Empresas do pool coletivo')),
                ('funcoes_coletivo', models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_funcao', to='funcoes.funcao', verbose_name='Funções do pool coletivo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('setores_coletivo', models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_setor', to='setores.setor', verbose_name='Setores do pool coletivo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, AppCore.core.users_permissions.user_permission_mixin.UserModelPermissionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImportacaoLote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('arquivo', models.TextField(max_length=100, verbose_name='Arquivo de Importação')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('total_linhas', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('linhas_processadas', models.IntegerField(default=0, verbose_name='Linhas Processadas')),
                ('resultado_json', models.JSONField(blank=True, null=True, verbose_name='Resultado/Erros')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Importação de Lote de Usuários',
                'verbose_name_plural': 'historical Importações de Lote de Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='CPF')),
                ('foto', models.URLField(blank=True, help_text='URL pública da foto vinda de sistemas externos.', max_length=500, null=True, verbose_name='Foto primária')),
                ('foto_secundaria', models.CharField(blank=True, help_text='Chave S3 da foto enviada pelo próprio usuário (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto secundária')),
                ('deficiencia', models.CharField(blank=True, choices=[('deficiencia_intelectual', 'Deficiência Intelectual'), ('deficiencia_visual', 'Deficiência Visual'), ('deficiencia_auditiva', 'Deficiência Auditiva'), ('deficiencia_multipla', 'Deficiência Múltipla'), ('deficiencia_fisica', 'Deficiência Física')], max_length=50, null=True, verbose_name='Deficiência / necessidade especial')),
                ('colaborador_externo', models.BooleanField(default=False, help_text='Indica se o usuário é colaborador externo à instituição.', verbose_name='Colaborador externo')),
                ('usuario_coletivo', models.BooleanField(default=False, help_text='Conta compartilhada (ex.: guarita). No empréstimo, o responsável deve ser escolhido entre os usuários do pool associado.', verbose_name='Usuário coletivo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuário',
                'verbose_name_plural': 'historical Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportacaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='importacoes/usuarios/%Y/%m/%d/', verbose_name='Arquivo de Importação')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('total_linhas', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('linhas_processadas', models.IntegerField(default=0, verbose_name='Linhas Processadas')),
                ('resultado_json', models.JSONField(blank=True, null=True, verbose_name='Resultado/Erros')),
            ],
            options={
                'verbose_name': 'Importação de Lote de Usuários',
                'verbose_name_plural': 'Importações de Lote de Usuários',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'EM_ANDAMENTO')), fields=('status',), name='usuarios_importacao_lote_unico_em_andamento')],
            },
        ),
    ]
