# Generated by Django 5.2.7 on 2026-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_importacaolote_historicalimportacaolote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
