# Generated by Django 5.2.14 on 2026-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_historicalusuario_deficiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='deficiencia',
            field=models.CharField(blank=True, choices=[('deficiencia_intelectual', 'Deficiência Intelectual'), ('baixa_visao', 'Baixa Visão'), ('deficiencia_auditiva', 'Deficiência Auditiva'), ('surdez', 'Surdez'), ('deficiencia_multipla', 'Deficiência Múltipla'), ('deficiencia_fisica', 'Deficiência Física')], max_length=50, null=True, verbose_name='Deficiência / necessidade especial'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='deficiencia',
            field=models.CharField(blank=True, choices=[('deficiencia_intelectual', 'Deficiência Intelectual'), ('baixa_visao', 'Baixa Visão'), ('deficiencia_auditiva', 'Deficiência Auditiva'), ('surdez', 'Surdez'), ('deficiencia_multipla', 'Deficiência Múltipla'), ('deficiencia_fisica', 'Deficiência Física')], max_length=50, null=True, verbose_name='Deficiência / necessidade especial'),
        ),
    ]
