# Generated by Django 5.2.14 on 2026-06-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_historicalusuario_deficiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='deficiencia',
            field=models.CharField(blank=True, choices=[('deficiencia_intelectual', 'Deficiência Intelectual'), ('deficiencia_visual', 'Deficiência Visual'), ('deficiencia_auditiva', 'Deficiência Auditiva'), ('deficiencia_multipla', 'Deficiência Múltipla'), ('deficiencia_fisica', 'Deficiência Física')], max_length=50, null=True, verbose_name='Deficiência / necessidade especial'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='deficiencia',
            field=models.CharField(blank=True, choices=[('deficiencia_intelectual', 'Deficiência Intelectual'), ('deficiencia_visual', 'Deficiência Visual'), ('deficiencia_auditiva', 'Deficiência Auditiva'), ('deficiencia_multipla', 'Deficiência Múltipla'), ('deficiencia_fisica', 'Deficiência Física')], max_length=50, null=True, verbose_name='Deficiência / necessidade especial'),
        ),
    ]
