# Generated by Django 5.2.14 on 2026-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='foto_secundaria',
            field=models.URLField(blank=True, help_text='URL pública da foto enviada pelo próprio usuário no S3.', max_length=500, null=True, verbose_name='Foto secundária'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_secundaria',
            field=models.URLField(blank=True, help_text='URL pública da foto enviada pelo próprio usuário no S3.', max_length=500, null=True, verbose_name='Foto secundária'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='foto',
            field=models.URLField(blank=True, help_text='URL pública da foto vinda de sistemas externos.', max_length=500, null=True, verbose_name='Foto primária'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.URLField(blank=True, help_text='URL pública da foto vinda de sistemas externos.', max_length=500, null=True, verbose_name='Foto primária'),
        ),
    ]
