# Generated by Django 5.2.14 on 2026-07-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_colaborador_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='foto_secundaria',
            field=models.URLField(blank=True, help_text='Chave S3 da foto enviada pelo próprio usuário (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto secundária'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_secundaria',
            field=models.URLField(blank=True, help_text='Chave S3 da foto enviada pelo próprio usuário (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto secundária'),
        ),
    ]
