# Generated by Django 5.2.14 on 2026-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_inserir_cargos_raizes'),
        ('empresas_instituicoes', '0002_inserir_empresas_raizes'),
        ('funcoes', '0004_popular_categoria_funcoes'),
        ('setores', '0002_inserir_setores_raizes'),
        ('usuarios', '0010_alter_historicalusuario_foto_secundaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='usuario_coletivo',
            field=models.BooleanField(default=False, help_text='Conta compartilhada (ex.: guarita). No empréstimo, o responsável deve ser escolhido entre os usuários do pool associado.', verbose_name='Usuário coletivo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargos_coletivo',
            field=models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_cargo', to='cargos.cargo', verbose_name='Cargos do pool coletivo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresas_coletivo',
            field=models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_empresa', to='empresas_instituicoes.empresainstituicao', verbose_name='Empresas do pool coletivo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcoes_coletivo',
            field=models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_funcao', to='funcoes.funcao', verbose_name='Funções do pool coletivo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='setores_coletivo',
            field=models.ManyToManyField(blank=True, related_name='usuarios_coletivos_por_setor', to='setores.setor', verbose_name='Setores do pool coletivo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_coletivo',
            field=models.BooleanField(default=False, help_text='Conta compartilhada (ex.: guarita). No empréstimo, o responsável deve ser escolhido entre os usuários do pool associado.', verbose_name='Usuário coletivo'),
        ),
    ]
