# Generated by Django 5.2.14 on 2026-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuario_coletivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='foto_secundaria',
            field=models.CharField(blank=True, help_text='Chave S3 da foto enviada pelo próprio usuário (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto secundária'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_secundaria',
            field=models.CharField(blank=True, help_text='Chave S3 da foto enviada pelo próprio usuário (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto secundária'),
        ),
    ]
