# Generated by Django 5.2.14 on 2026-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='exige_aluno',
            field=models.BooleanField(default=False, verbose_name='Exige Aluno'),
        ),
        migrations.AddField(
            model_name='historicalfuncao',
            name='exige_aluno',
            field=models.BooleanField(default=False, verbose_name='Exige Aluno'),
        ),
    ]
