# Generated by Django 5.2.14 on 2026-07-13 20:39

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('chave', 'Chave'), ('midia', 'Mídia'), ('material_didatico', 'Material didático')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='Descrição')),
                ('em_avaria', models.BooleanField(default=False, verbose_name='Em avaria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'historical Recurso',
                'verbose_name_plural': 'historical Recursos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('chave', 'Chave'), ('midia', 'Mídia'), ('material_didatico', 'Material didático')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='Descrição')),
                ('em_avaria', models.BooleanField(default=False, verbose_name='Em avaria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['codigo'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, models.Model),
        ),
    ]
