# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('chave', 'Chave'), ('midia', 'Mídia'), ('material_didatico', 'Material didático')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='Descrição')),
                ('foto', models.CharField(blank=True, help_text='Chave S3 da foto enviada no cadastro (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto')),
                ('em_avaria', models.BooleanField(default=False, verbose_name='Em avaria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Recurso',
                'verbose_name_plural': 'historical Recursos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('chave', 'Chave'), ('midia', 'Mídia'), ('material_didatico', 'Material didático')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, default='', max_length=500, verbose_name='Descrição')),
                ('foto', models.CharField(blank=True, help_text='Chave S3 da foto enviada no cadastro (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto')),
                ('em_avaria', models.BooleanField(default=False, verbose_name='Em avaria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['codigo'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
    ]
