# Generated by Django 5.2.14 on 2026-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_recurso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecurso',
            name='foto',
            field=models.CharField(blank=True, help_text='Chave S3 da foto enviada no cadastro (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='foto',
            field=models.CharField(blank=True, help_text='Chave S3 da foto enviada no cadastro (servida via proxy da API).', max_length=500, null=True, verbose_name='Foto'),
        ),
    ]
