# Generated by Django 5.2.7 on 2026-05-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0002_inserir_setores_raizes'),
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorvinculo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='setores.setor', verbose_name='Setor'),
        ),
    ]
