# Generated by Django 5.2.14 on 2026-07-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorvinculo',
            options={'ordering': ['setor__nome', 'usuario__nome'], 'verbose_name': 'Vínculo de Setor', 'verbose_name_plural': 'Vínculos de Setor'},
        ),
    ]
