# Generated by Django 5.2.7 on 2026-05-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcoes', '0003_inserir_funcoes_raizes'),
        ('vinculos', '0002_alter_setorvinculo_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorvinculo',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='funcoes.funcao', verbose_name='Função'),
        ),
    ]
