# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import simple_history.models
from django.db import migrations, models


def inserir_empresas_raizes(apps, schema_editor):
    EmpresaInstituicao = apps.get_model('empresas_instituicoes', 'EmpresaInstituicao')

    empresas = [
        {"nome": "CASTELO SERVIÇOS DE SEGURANÇA LTDA.", "cnpj": None, "ativo": True},
        {"nome": "SERVFAZ SERVIÇOS DE MÃO DE OBRA LTDA.", "cnpj": None, "ativo": True},
        {"nome": "SERVIRE AGENCIAMENTO DE MÃO DE OBRA LTDA.", "cnpj": None, "ativo": True},
    ]

    for empresa_data in empresas:
        EmpresaInstituicao.objects.get_or_create(
            nome=empresa_data['nome'],
            defaults={
                'cnpj': empresa_data['cnpj'],
                'ativo': empresa_data['ativo'],
            }
        )


def remover_empresas_raizes(apps, schema_editor):
    EmpresaInstituicao = apps.get_model('empresas_instituicoes', 'EmpresaInstituicao')
    nomes = [
        "CASTELO SERVIÇOS DE SEGURANÇA LTDA.",
        "SERVFAZ SERVIÇOS DE MÃO DE OBRA LTDA.",
        "SERVIRE AGENCIAMENTO DE MÃO DE OBRA LTDA.",
    ]
    EmpresaInstituicao.objects.filter(nome__in=nomes).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Empresa/Instituição',
                'verbose_name_plural': 'Empresas/Instituições',
                'ordering': ['nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmpresaInstituicao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Empresa/Instituição',
                'verbose_name_plural': 'historical Empresas/Instituições',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(inserir_empresas_raizes, reverse_code=remover_empresas_raizes),
    ]
