# Generated by Django 5.2.14 on 2026-05-22 02:04

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas_instituicoes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTerceirizado',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('cargo_funcao', models.CharField(help_text='Cargo ou função exercida pelo terceirizado na instituição.', max_length=255, verbose_name='Cargo/Função')),
                ('data_inicio', models.DateField(help_text='Data de início do vínculo terceirizado.', verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término do vínculo. Nulo indica vínculo em aberto.', null=True, verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas_instituicoes.empresainstituicao', verbose_name='Empresa/Instituição')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Terceirizado',
                'verbose_name_plural': 'historical Terceirizados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Terceirizado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='terceirizado', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('cargo_funcao', models.CharField(help_text='Cargo ou função exercida pelo terceirizado na instituição.', max_length=255, verbose_name='Cargo/Função')),
                ('data_inicio', models.DateField(help_text='Data de início do vínculo terceirizado.', verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término do vínculo. Nulo indica vínculo em aberto.', null=True, verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceirizados', to='empresas_instituicoes.empresainstituicao', verbose_name='Empresa/Instituição')),
            ],
            options={
                'verbose_name': 'Terceirizado',
                'verbose_name_plural': 'Terceirizados',
                'ordering': ['usuario__nome'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, models.Model),
        ),
    ]
