# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0002_initial'),
        ('empresas_instituicoes', '0002_initial'),
        ('terceirizados', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalterceirizado',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargos.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='historicalterceirizado',
            name='empresa_instituicao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empresas_instituicoes.empresainstituicao', verbose_name='Empresa/Instituição'),
        ),
        migrations.AddField(
            model_name='historicalterceirizado',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalterceirizado',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Terceirizado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='terceirizado', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início do vínculo terceirizado.', null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término do vínculo. Nulo indica vínculo em aberto.', null=True, verbose_name='Data de Término')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceirizados', to='cargos.cargo', verbose_name='Cargo')),
                ('empresa_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceirizados', to='empresas_instituicoes.empresainstituicao', verbose_name='Empresa/Instituição')),
            ],
            options={
                'verbose_name': 'Terceirizado',
                'verbose_name_plural': 'Terceirizados',
                'ordering': ['usuario__nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('matricula__isnull', False)), fields=('matricula',), name='terceirizados_matricula_unica')],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
    ]
