# Generated by Django 5.2.7 on 2026-05-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalterceirizado',
            old_name='empresa',
            new_name='empresa_instituicao',
        ),
        migrations.RenameField(
            model_name='terceirizado',
            old_name='empresa',
            new_name='empresa_instituicao',
        ),
    ]
