# Generated by Django 5.2.7 on 2026-05-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizados', '0002_rename_empresa_historicalterceirizado_empresa_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalterceirizado',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data de início do vínculo terceirizado.', null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='terceirizado',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data de início do vínculo terceirizado.', null=True, verbose_name='Data de Início'),
        ),
    ]
