# Generated by Django 5.2.14 on 2026-06-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_inserir_cargos_raizes'),
        ('terceirizados', '0003_alter_historicalterceirizado_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalterceirizado',
            name='cargo_funcao',
        ),
        migrations.RemoveField(
            model_name='terceirizado',
            name='cargo_funcao',
        ),
        migrations.AddField(
            model_name='historicalterceirizado',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargos.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='terceirizado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceirizados', to='cargos.cargo', verbose_name='Cargo'),
        ),
    ]
