# Generated by Django 5.2.14 on 2026-08-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_inserir_cursos_raizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='historicalcurso',
            name='turno',
        ),
    ]
