# Generated by Django 5.2.14 on 2026-08-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strikes', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstrike',
            name='ticket',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='strike',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='strike', to='tickets.ticket', verbose_name='Ticket'),
        ),
    ]
