from django.urls import path

from AppCore.basics.views.basic_views import roteador_por_metodo

from .views import (
    AbrirReservasExecucaoRotaView,
    CancelarExecucaoRotaView,
    CriarExecucaoRotaView,
    DetalharExecucaoRotaView,
    DetalharHistoricoConferenciaView,
    DetalharHistoricoRotaView,
    FecharReservasExecucaoRotaView,
    AusentarTicketConferenciaView,
    DesfazerAusenciaTicketConferenciaView,
    DesfazerPresencaTicketConferenciaView,
    EmbarcarTicketConferenciaView,
    FecharPrimeiraChamadaConferenciaView,
    FecharSegundaChamadaConferenciaView,
    FinalizarExecucaoRotaView,
    RestantesFaltaramConferenciaView,
    FinalizarViagemRotaView,
    IniciarEmbarqueExecucaoRotaView,
    IniciarViagemRotaView,
    ListarExecucoesConferenciaView,
    ListarExecucoesRotasView,
    ListarHistoricoConferenciaView,
    ListarHistoricoRotasView,
    ListarPercursosHistoricoConferenciaView,
    ListarPercursosHistoricoView,
    ListarReservasConferenciaView,
)

urlpatterns = [
    path(
        'motorista/historico-rotas/',
        ListarHistoricoRotasView.as_view(),
        name='motorista-historico-rotas-list',
    ),
    path(
        'motorista/historico-rotas/percursos/',
        ListarPercursosHistoricoView.as_view(),
        name='motorista-historico-percursos-list',
    ),
    path(
        'motorista/historico-rotas/<int:pk>/',
        DetalharHistoricoRotaView.as_view(),
        name='motorista-historico-rotas-detail',
    ),
    path(
        'execucoes-rotas/<int:pk>/motorista/iniciar-rota/',
        roteador_por_metodo(POST=IniciarViagemRotaView),
        name='motorista-iniciar-rota',
    ),
    path(
        'execucoes-rotas/<int:pk>/motorista/finalizar-rota/',
        roteador_por_metodo(POST=FinalizarViagemRotaView),
        name='motorista-finalizar-rota',
    ),
    path(
        'execucoes-rotas/',
        roteador_por_metodo(GET=ListarExecucoesRotasView, POST=CriarExecucaoRotaView),
        name='execucao-rota-list',
    ),
    path(
        'execucoes-rotas/conferencia/',
        roteador_por_metodo(GET=ListarExecucoesConferenciaView),
        name='conferencia-execucao-list',
    ),
    path(
        'execucoes-rotas/historico/',
        ListarHistoricoConferenciaView.as_view(),
        name='execucao-rota-historico-list',
    ),
    path(
        'execucoes-rotas/historico/percursos/',
        ListarPercursosHistoricoConferenciaView.as_view(),
        name='execucao-rota-historico-percursos-list',
    ),
    path(
        'execucoes-rotas/historico/<int:pk>/',
        DetalharHistoricoConferenciaView.as_view(),
        name='execucao-rota-historico-detail',
    ),
    path(
        'execucoes-rotas/<int:pk>/',
        roteador_por_metodo(GET=DetalharExecucaoRotaView),
        name='execucao-rota-detalhe',
    ),
    path(
        'execucoes-rotas/<int:pk>/abrir-reservas/',
        roteador_por_metodo(POST=AbrirReservasExecucaoRotaView),
        name='execucao-rota-abrir-reservas',
    ),
    path(
        'execucoes-rotas/<int:pk>/fechar-reservas/',
        roteador_por_metodo(POST=FecharReservasExecucaoRotaView),
        name='execucao-rota-fechar-reservas',
    ),
    path(
        'execucoes-rotas/<int:pk>/cancelar/',
        roteador_por_metodo(POST=CancelarExecucaoRotaView),
        name='execucao-rota-cancelar',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/iniciar/',
        roteador_por_metodo(POST=IniciarEmbarqueExecucaoRotaView),
        name='conferencia-iniciar',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/finalizar/',
        roteador_por_metodo(POST=FinalizarExecucaoRotaView),
        name='conferencia-finalizar',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/reservas/',
        roteador_por_metodo(GET=ListarReservasConferenciaView),
        name='conferencia-reservas',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/fechar-primeira-chamada/',
        roteador_por_metodo(POST=FecharPrimeiraChamadaConferenciaView),
        name='conferencia-fechar-primeira-chamada',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/fechar-segunda-chamada/',
        roteador_por_metodo(POST=FecharSegundaChamadaConferenciaView),
        name='conferencia-fechar-segunda-chamada',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/restantes-faltaram/',
        roteador_por_metodo(POST=RestantesFaltaramConferenciaView),
        name='conferencia-restantes-faltaram',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/tickets/<uuid:codigo>/embarcar/',
        roteador_por_metodo(POST=EmbarcarTicketConferenciaView),
        name='conferencia-ticket-embarcar',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/tickets/<uuid:codigo>/desfazer-presenca/',
        roteador_por_metodo(POST=DesfazerPresencaTicketConferenciaView),
        name='conferencia-ticket-desfazer-presenca',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/tickets/<uuid:codigo>/ausentar/',
        roteador_por_metodo(POST=AusentarTicketConferenciaView),
        name='conferencia-ticket-ausentar',
    ),
    path(
        'execucoes-rotas/<int:pk>/conferencia/tickets/<uuid:codigo>/desfazer-ausencia/',
        roteador_por_metodo(POST=DesfazerAusenciaTicketConferenciaView),
        name='conferencia-ticket-desfazer-ausencia',
    ),
]
