# Generated by Django 5.2.7 on 2026-05-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['usuario__nome'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
