# Generated by Django 5.2.7 on 2026-05-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['matricula'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
    ]
