# Generated by Django 5.2.14 on 2026-08-31 18:50

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import AppCore.core.state.state_mixin
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0003_alter_aluno_ira_alter_historicalaluno_ira'),
        ('execucoes_rotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Código público')),
                ('status', models.IntegerField(choices=[(1, 'Reservado'), (2, 'Em espera'), (3, 'Cancelado'), (4, 'Embarcado'), (5, 'Ausente')], verbose_name='Status')),
                ('reservado_em', models.DateTimeField(blank=True, null=True, verbose_name='Reservado em')),
                ('entrou_em_espera_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrou em espera em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('embarcado_em', models.DateTimeField(blank=True, null=True, verbose_name='Embarcado em')),
                ('ausente_em', models.DateTimeField(blank=True, null=True, verbose_name='Ausente em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aluno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alunos.aluno', verbose_name='Aluno')),
                ('execucao_rota', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='execucoes_rotas.execucaorota', verbose_name='Execução da rota')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ticket',
                'verbose_name_plural': 'historical Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código público')),
                ('status', models.IntegerField(choices=[(1, 'Reservado'), (2, 'Em espera'), (3, 'Cancelado'), (4, 'Embarcado'), (5, 'Ausente')], verbose_name='Status')),
                ('reservado_em', models.DateTimeField(blank=True, null=True, verbose_name='Reservado em')),
                ('entrou_em_espera_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrou em espera em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('embarcado_em', models.DateTimeField(blank=True, null=True, verbose_name='Embarcado em')),
                ('ausente_em', models.DateTimeField(blank=True, null=True, verbose_name='Ausente em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_transporte', to='alunos.aluno', verbose_name='Aluno')),
                ('execucao_rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='execucoes_rotas.execucaorota', verbose_name='Execução da rota')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execucao_rota', 'status'], name='ticket_execucao_status_idx'), models.Index(fields=['status', 'entrou_em_espera_em'], name='ticket_fila_ordem_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 3), _negated=True), fields=('execucao_rota', 'aluno'), name='ticket_ativo_unico_aluno_execucao')],
            },
            bases=(AppCore.core.state.state_mixin.ModelStateMixin, AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
    ]
