# Generated by Django 5.2.14 on 2026-09-10 00:48

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import AppCore.core.state.state_mixin
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Código público')),
                ('status', models.IntegerField(choices=[(1, 'Reservado'), (2, 'Em espera'), (3, 'Cancelado'), (4, 'Embarcado'), (5, 'Ausente'), (7, 'Contemplado')], verbose_name='Status')),
                ('reservado_em', models.DateTimeField(blank=True, null=True, verbose_name='Reservado em')),
                ('entrou_em_espera_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrou em espera em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('embarcado_em', models.DateTimeField(blank=True, null=True, verbose_name='Embarcado em')),
                ('ausente_em', models.DateTimeField(blank=True, null=True, verbose_name='Ausente em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Ticket',
                'verbose_name_plural': 'historical Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código público')),
                ('status', models.IntegerField(choices=[(1, 'Reservado'), (2, 'Em espera'), (3, 'Cancelado'), (4, 'Embarcado'), (5, 'Ausente'), (7, 'Contemplado')], verbose_name='Status')),
                ('reservado_em', models.DateTimeField(blank=True, null=True, verbose_name='Reservado em')),
                ('entrou_em_espera_em', models.DateTimeField(blank=True, null=True, verbose_name='Entrou em espera em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('embarcado_em', models.DateTimeField(blank=True, null=True, verbose_name='Embarcado em')),
                ('ausente_em', models.DateTimeField(blank=True, null=True, verbose_name='Ausente em')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
            bases=(AppCore.core.state.state_mixin.ModelStateMixin, AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
    ]
