# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('execucoes_rotas', '0003_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='aluno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='execucao_rota',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='execucoes_rotas.execucaorota', verbose_name='Execução da rota'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_transporte', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='execucao_rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='execucoes_rotas.execucaorota', verbose_name='Execução da rota'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['execucao_rota', 'status'], name='ticket_execucao_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'entrou_em_espera_em'], name='ticket_fila_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 3), _negated=True), fields=('execucao_rota', 'aluno'), name='ticket_ativo_unico_aluno_execucao'),
        ),
    ]
