# Generated by Django 5.2.14 on 2026-09-15 22:21

from django.db import migrations, models


STATUS_COM_POSICAO_RESERVA = (1, 4, 5)


def preencher_posicoes_reserva(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    execucoes_ids = (
        Ticket.objects.filter(status__in=STATUS_COM_POSICAO_RESERVA)
        .values_list('execucao_rota_id', flat=True)
        .distinct()
    )
    for execucao_id in execucoes_ids.iterator():
        tickets = list(
            Ticket.objects.filter(
                execucao_rota_id=execucao_id,
                status__in=STATUS_COM_POSICAO_RESERVA,
            )
        )
        tickets.sort(
            key=lambda ticket: (
                ticket.reservado_em is None,
                ticket.reservado_em,
                ticket.pk,
            ),
        )
        for posicao, ticket in enumerate(tickets, start=1):
            ticket.posicao_reserva = posicao
        Ticket.objects.bulk_update(tickets, ['posicao_reserva'])


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('execucoes_rotas', '0004_conferencia_finalizada_por'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='posicao_reserva',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Posição da reserva'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='posicao_reserva',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Posição da reserva'),
        ),
        migrations.RunPython(
            preencher_posicoes_reserva,
            migrations.RunPython.noop,
        ),
    ]
