# Generated by Django 5.2.14 on 2026-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_contemplado_e_espera_legado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.IntegerField(
                choices=[
                    (1, 'Reservado'),
                    (2, 'Em espera'),
                    (3, 'Cancelado'),
                    (4, 'Embarcado'),
                    (5, 'Ausente'),
                    (7, 'Contemplado'),
                ],
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(
                choices=[
                    (1, 'Reservado'),
                    (2, 'Em espera'),
                    (3, 'Cancelado'),
                    (4, 'Embarcado'),
                    (5, 'Ausente'),
                    (7, 'Contemplado'),
                ],
                verbose_name='Status',
            ),
        ),
    ]
