# Generated by Django 5.2.14 on 2026-09-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('execucoes_rotas', '0004_conferencia_finalizada_por'),
        ('tickets', '0003_posicao_reserva_persistente'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', (1, 4, 5))),
                fields=('execucao_rota', 'posicao_reserva'),
                name='ticket_posicao_reserva_ativa_unica',
            ),
        ),
    ]
