PERMISSAO_CORTEX_EDITAR_EU = 'EDITAR_EU'
PERMISSAO_CORTEX_LER_TUDO = 'LER_TUDO'
PERMISSAO_CORTEX_EDITAR_TUDO = 'EDITAR_TUDO'

NIVEL_CORTEX = {
    PERMISSAO_CORTEX_EDITAR_EU: 1,
    PERMISSAO_CORTEX_LER_TUDO: 2,
    PERMISSAO_CORTEX_EDITAR_TUDO: 3,
}
