# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('justificativas', '0001_initial'),
        ('strikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljustificativa',
            name='aluno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='historicaljustificativa',
            name='analisada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Analisada por'),
        ),
        migrations.AddField(
            model_name='historicaljustificativa',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificativa',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificativas_transporte', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='justificativa',
            name='analisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justificativas_transporte_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analisada por'),
        ),
        migrations.AddField(
            model_name='justificativa',
            name='strikes_cobertos',
            field=models.ManyToManyField(related_name='justificativas', to='strikes.strike', verbose_name='Strikes cobertos'),
        ),
    ]
