# Generated by Django 5.2.14 on 2026-08-31 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('justificativas', '0001_initial'),
        ('strikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljustificativa',
            name='strike',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strikes.strike', verbose_name='Strike'),
        ),
        migrations.AddField(
            model_name='justificativa',
            name='analisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justificativas_transporte_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analisada por'),
        ),
        migrations.AddField(
            model_name='justificativa',
            name='strike',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='justificativa', to='strikes.strike', verbose_name='Strike'),
        ),
    ]
