# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='historicalemprestimo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemprestimo',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='historicalemprestimo',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='historicalitememprestimo',
            name='emprestimo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emprestimos.emprestimo', verbose_name='Empréstimo'),
        ),
        migrations.AddField(
            model_name='historicalitememprestimo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitememprestimo',
            name='recurso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recursos.recurso', verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='emprestimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='emprestimos.emprestimo', verbose_name='Empréstimo'),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_emprestimo', to='recursos.recurso', verbose_name='Recurso'),
        ),
        migrations.AddConstraint(
            model_name='itememprestimo',
            constraint=models.UniqueConstraint(condition=models.Q(('devolvido_em__isnull', True)), fields=('recurso',), name='emprestimos_item_recurso_unico_aberto'),
        ),
    ]
