# Generated by Django 5.2.14 on 2026-07-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_inserir_cargo_servente_limpeza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['solicitante__nome', '-retirada_em'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='itememprestimo',
            options={'ordering': ['recurso__codigo'], 'verbose_name': 'Item de empréstimo', 'verbose_name_plural': 'Itens de empréstimo'},
        ),
    ]
