# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('entradas_sem_ticket', '0001_initial'),
        ('execucoes_rotas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasemticket',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_sem_ticket', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='entradasemticket',
            name='execucao_rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_sem_ticket', to='execucoes_rotas.execucaorota', verbose_name='Execução da rota'),
        ),
        migrations.AddField(
            model_name='historicalentradasemticket',
            name='aluno',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='historicalentradasemticket',
            name='execucao_rota',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='execucoes_rotas.execucaorota', verbose_name='Execução da rota'),
        ),
        migrations.AddField(
            model_name='historicalentradasemticket',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='entradasemticket',
            constraint=models.UniqueConstraint(fields=('execucao_rota', 'aluno'), name='entrada_sem_ticket_unica_aluno_execucao'),
        ),
    ]
