# Generated by Django 5.2.14 on 2026-07-14 11:50

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import AppCore.core.rules.rules_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, help_text='Nulo indica autorização permanente.', null=True, verbose_name='Data de fim')),
                ('revogado_em', models.DateTimeField(blank=True, null=True, verbose_name='Revogado em')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_infraestrutura', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiário')),
                ('concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_concedidas', to=settings.AUTH_USER_MODEL, verbose_name='Concedente')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='recursos.recurso', verbose_name='Recurso')),
                ('revogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_revogadas', to=settings.AUTH_USER_MODEL, verbose_name='Revogador')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
                'ordering': ['-data_inicio', '-created_at'],
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, AppCore.core.rules.rules_mixin.ModelRulesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAutorizacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, help_text='Nulo indica autorização permanente.', null=True, verbose_name='Data de fim')),
                ('revogado_em', models.DateTimeField(blank=True, null=True, verbose_name='Revogado em')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beneficiario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiário')),
                ('concedente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Concedente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recursos.recurso', verbose_name='Recurso')),
                ('revogador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revogador')),
                ('sala', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'historical Autorização',
                'verbose_name_plural': 'historical Autorizações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
