# Generated by Django 5.2.14 on 2026-09-10 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizacoes', '0001_initial'),
        ('recursos', '0001_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_infraestrutura', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiário'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_concedidas', to=settings.AUTH_USER_MODEL, verbose_name='Concedente'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='recursos.recurso', verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='revogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes_revogadas', to=settings.AUTH_USER_MODEL, verbose_name='Revogador'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizacoes', to='salas.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='historicalautorizacao',
            name='beneficiario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiário'),
        ),
        migrations.AddField(
            model_name='historicalautorizacao',
            name='concedente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Concedente'),
        ),
        migrations.AddField(
            model_name='historicalautorizacao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalautorizacao',
            name='recurso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recursos.recurso', verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='historicalautorizacao',
            name='revogador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revogador'),
        ),
        migrations.AddField(
            model_name='historicalautorizacao',
            name='sala',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salas.sala', verbose_name='Sala'),
        ),
    ]
