# Generated by Django 5.2.14 on 2026-07-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacao',
            options={'ordering': ['beneficiario__nome', 'recurso__codigo', 'sala__bloco__nome', 'sala__nome'], 'verbose_name': 'Autorização', 'verbose_name_plural': 'Autorizações'},
        ),
    ]
