# Generated by Django 5.2.14 on 2026-05-23 20:23

import AppCore.core.business.business_mixin
import AppCore.core.helpers.helpers_mixin
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aluno', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ira', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='IRA')),
                ('situacao', models.IntegerField(choices=[(1, 'Matriculado'), (2, 'Trancado'), (3, 'Formado'), (4, 'Desistente'), (5, 'Transferido')], default=1, verbose_name='Situação')),
                ('forma_ingresso', models.IntegerField(choices=[(1, 'Vestibular'), (2, 'ENEM'), (3, 'Transferência'), (4, 'Reingresso')], default=1, verbose_name='Forma de Ingresso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
            bases=(AppCore.core.helpers.helpers_mixin.ModelHelperMixin, AppCore.core.business.business_mixin.ModelBusinessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAluno',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('ira', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='IRA')),
                ('situacao', models.IntegerField(choices=[(1, 'Matriculado'), (2, 'Trancado'), (3, 'Formado'), (4, 'Desistente'), (5, 'Transferido')], default=1, verbose_name='Situação')),
                ('forma_ingresso', models.IntegerField(choices=[(1, 'Vestibular'), (2, 'ENEM'), (3, 'Transferência'), (4, 'Reingresso')], default=1, verbose_name='Forma de Ingresso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Aluno',
                'verbose_name_plural': 'historical Alunos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
