# Generated by Django 5.2.14 on 2026-05-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['usuario__nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
