# Generated by Django 5.2.7 on 2026-05-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ira',
            field=models.FloatField(default=0.0, verbose_name='IRA'),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='ira',
            field=models.FloatField(default=0.0, verbose_name='IRA'),
        ),
    ]
